/* ***** BEGIN COPYRIGHT AND LICENSE BLOCK *****
 *
 * Copyright © 2010 Hector Zhao
 *
 * This file is part of FireBBS.l-hedgehog.
 *
 * FireBBS.l-hedgehog is free software: you can redistribute it
 * and/or modify it under the terms of the GNU General Public License
 * as published by the Free Software Foundation, either version 3 of
 * the License, or (at your option) any later version.
 *
 * FireBBS.l-hedgehog is distributed in the hope that it will be
 * useful, but WITHOUT ANY WARRANTY; without even the implied warranty
 * of MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License
 * along with FireBBS.l-hedgehog.  If not, see <http://www.gnu.org/licenses/>.
 *
 * ***** END COPYRIGHT AND LICENSE BLOCK ***** */

#include "nsISupports.idl"

/**
 * Find the address of the given ip in QQwry.dat
 */
 
[scriptable, uuid(5665b472-3c7a-4ef7-ab12-a8de8a5a3338)]
interface hzIIPSearcherService : nsISupports
{

    /**
     * Init the hzIPSearcher service
     *
     * Read data from QQwry.dat, get the start position of the index.
     * An exception will be thrown if QQwry.dat cannot be found.
     */
    void init();

    /**
     * Find the address of the given ip.
     *
     * @param aIP - The ip to lookup in QQwry.dat.
     */
    AString location(in ACString aIP);

};
